### ISSUE TITLE
Bug in lessons/new

### ISSUE THREAD

**Issue by almightyboz** [rubyforgood/justice#25] opened 2017-05-20 14:01 UTC
The "term" field shows an AR association collection proxy object( eg. #<Term::ActiveRecord_Associations_CollectionProxy:0x007fa24ef5deb0>), not the plaintext term itself. 

Use a select_to drop-down instead, because a lesson can have many terms.
Should also have functionality to add a new term through that page instead of having to go to a new page to add a term

**Comment by jmkoni** [comment] 2017-05-20 16:25
Hey I am going to close this because this is being fixed as part of integrating the design into the scaffolded lessons page. So, not a bug, but actually intentionally not done.

**Closed as completed by jmkoni** 2017-05-20 16:25 UTC
